# Generated by Django 5.0.3 on 2024-07-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='tile',
            new_name='title',
        ),
    ]
